In [2]:
fig = px.box(
    df,
    x="condition",
    y="price",
    title="Preço dos veículos por condição"
    )
fig.update_xaxes(title="Condição")
fig.update_yaxes(title="Preço")

fig.show()

NameError: name 'px' is not defined

In [ ]:
fig = px.box(df, x="condition", y="price")
fig.show()

In [ ]:
fig = px.histogram(df, x="type")
fig.show()

In [ ]:
fig = px.histogram(df, x="transmission")
fig.show()

In [ ]:
fig = px.histogram(df, x="fuel")
fig.show()

In [ ]:
fig = px.histogram(df, x="condition")
fig.show()

In [ ]:
fig = px.histogram(df, x="model_year")
fig.show()

In [ ]:
fig = px.histogram(df, x="price")
fig.show()

In [ ]:
df.isnull().sum()

price               0
model_year       3619
model               0
condition           0
cylinders        5260
fuel                0
odometer         7892
transmission        0
type                0
paint_color      9267
is_4wd          25953
date_posted         0
days_listed         0
dtype: int64

In [ ]:
df.describe()

,price,model_year,cylinders,odometer,is_4wd,days_listed
count,51525.000000,47906.000000,46265.000000,43633.000000,25572.0,51525.00000
mean,12132.464920,2009.750470,6.125235,115553.461738,1.0,39.55476
std,10040.803015,6.282065,1.660360,65094.611341,0.0,28.20427
min,1.000000,1908.000000,3.000000,0.000000,1.0,0.00000
25%,5000.000000,2006.000000,4.000000,70000.000000,1.0,19.00000
50%,9000.000000,2011.000000,6.000000,113000.000000,1.0,33.00000
75%,16839.000000,2014.000000,8.000000,155000.000000,1.0,53.00000
max,375000.000000,2019.000000,12.000000,990000.000000,1.0,271.00000

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51525 entries, 0 to 51524
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   price         51525 non-null  int64
 1   model_year    47906 non-null  float64
 2   model         51525 non-null  str
 3   condition     51525 non-null  str
 4   cylinders     46265 non-null  float64
 5   fuel          51525 non-null  str
 6   odometer      43633 non-null  float64
 7   transmission  51525 non-null  str
 8   type          51525 non-null  str
 9   paint_color   42258 non-null  str
 10  is_4wd        25572 non-null  float64
 11  date_posted   51525 non-null  str
 12  days_listed   51525 non-null  int64
dtypes: float64(4), int64(2), str(7)
memory usage: 7.7 MB

In [ ]:
df = pd.read_csv("../vehicles.csv")
df.head()

,price,model_year,model,condition,cylinders,fuel,odometer,transmission,type,paint_color,is_4wd,date_posted,days_listed
0,9400,2011.0,bmw x5,good,6.0,gas,145000.0,automatic,SUV,NaN,1.0,2018-06-23,19
1,25500,NaN,ford f-150,good,6.0,gas,88705.0,automatic,pickup,white,1.0,2018-10-19,50
2,5500,2013.0,hyundai sonata,like new,4.0,gas,110000.0,automatic,sedan,red,NaN,2019-02-07,79
3,1500,2003.0,ford f-150,fair,8.0,gas,NaN,automatic,pickup,NaN,NaN,2019-03-22,9
4,14900,2017.0,chrysler 200,excellent,4.0,gas,80903.0,automatic,sedan,black,NaN,2019-04-02,28

In [3]:
import pandas as pd
import plotly.express as px

car_data = pd.read_csv("../vehicles.csv")   

car_data.head()

,price,model_year,model,condition,cylinders,fuel,odometer,transmission,type,paint_color,is_4wd,date_posted,days_listed
0,9400,2011.0,bmw x5,good,6.0,gas,145000.0,automatic,SUV,NaN,1.0,2018-06-23,19
1,25500,NaN,ford f-150,good,6.0,gas,88705.0,automatic,pickup,white,1.0,2018-10-19,50
2,5500,2013.0,hyundai sonata,like new,4.0,gas,110000.0,automatic,sedan,red,NaN,2019-02-07,79
3,1500,2003.0,ford f-150,fair,8.0,gas,NaN,automatic,pickup,NaN,NaN,2019-03-22,9
4,14900,2017.0,chrysler 200,excellent,4.0,gas,80903.0,automatic,sedan,black,NaN,2019-04-02,28

In [4]:
fig = px.histogram(
    car_data,
    x="price",
    title="Distribuição de Preços dos Veículos"

)
fig.show()

In [5]:
fig = px.box(
    car_data,
    x="condition",
    y="price",
    title="Preço dos veículos por condição"
)
fig.show()

In [6]:
fig = px.scatter(
    car_data,
    x="odometer",
    y="price",
    color="condition",
    title="Preço dos veículos por quilometragem"
)
fig.show()